export enum Paths {
  EMPTY = "/",
  Root = "/",
  ID = "/:id",
  Login = "/login",
  SsoLogin = "/ssologin",
  Logout = "/logout",
  Auth = "/auth",
  Api = "/api",
  Product = "/product",
  User = "/user",
  Account = "/account",
  Cart = "/cart",
  Address = "/address",
  ProductApi = Paths.Api + Paths.Product,
  UserApi = Paths.Api + Paths.User,
  AccountApi = Paths.Api + Paths.Account,
  ResendVerification = "/resendverification",
  VerifyAccount = "/verify",
  ForgotPassword = "/forgotpassword",
  ResetPassword = "/resetpassword",
  CartApi = Paths.Api + Paths.Cart,
  AddressApi = Paths.Api + Paths.Address,
}
